config/routes.rb
Blimp::Engine.routes.draw do
  resources :uploads
end

app/models/blimp/application_record.rb
module Blimp
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blimp/upload.rb
module Blimp
  class Upload < ApplicationRecord
    validates_presence_of :datafile
    mount_uploader :datafile , DatafileUploader
  end
end

app/controllers/blimp/application_controller.rb
module Blimp
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/blimp/uploads_controller.rb
require 'tempfile'
require 'harvest_csv'
require_dependency "blimp/application_controller"

module Blimp
  class UploadsController < ApplicationController
    before_action :set_upload, only: [:show, :edit, :upload, :delete]

    # GET /uploads
    def index
      @uploads = Upload.all
    end

    # GET /uploads/1
    def show
    end

    # GET /uploads/new
    def new
      @upload = Upload.new
      @upload.map_filename = File.join(Rails.root, 'config', 'solr_map.yml')
    end

    # GET /uploads/1/edit
    def edit
    end

    # POST /uploads
    def create
      @upload = Upload.new(upload_params)

      if @upload.save
        FileUtils.rm(@upload.datafile.current_path) if FileTest.exist?(@upload.datafile.current_path)
        @upload.destroy
        redirect_to "/", notice: 'Upload was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /uploads/1
    def update
      if @upload.update(upload_params)
        redirect_to @upload, notice: 'Upload was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /uploads/1
    def destroy
      FileUtils.rm(@upload.datafile.current_path) if FileTest.exist?(@upload.datafile.current_path)
      FileUtils.rm(@upload.map_filename) if FileTest.exist?(@upload.map_filename)
      @upload.destroy
      redirect_to uploads_url, notice: 'Upload was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_upload
        @upload = Upload.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def upload_params
        params.require(:upload).permit(:map_filename, :id_field, :datafile)
      end
  end
end

app/helpers/blimp/application_helper.rb
module Blimp
  module ApplicationHelper
  end
end

app/helpers/blimp/uploads_helper.rb
module Blimp
  module UploadsHelper
  end
end

app/views/blimp/uploads/_form.html.erb
<%= form_for(upload) do |f| %>
  <% if upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% upload.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :map_filename %>
  </div>

  <div class="field">
    <%= f.label :datafile, "Upload data file:" %>
    <%= f.file_field :datafile %>
  </div>

  <div class="field">
    <%= f.label :id_field %>
    <%= f.text_field :id_field %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blimp/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/blimp/uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uploaded files</h1>

<table>
  <thead>
    <tr>
      <th>Map filename</th>
      <th>Id field</th>
      <th>Datafile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.map_filename %></td>
        <td><%= upload.id_field %></td>
        <td><%= upload.datafile %></td>
        <td><%= link_to 'Show', upload %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upload', new_upload_path %>

app/views/blimp/uploads/new.html.erb
<h1>New Upload</h1>

<%= render 'form', upload: @upload %>

<%= link_to 'Back', uploads_path %>

app/views/blimp/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Map filename:</strong>
  <%= @upload.map_filename %>
</p>

<p>
  <strong>Id field:</strong>
  <%= @upload.id_field %>
</p>

<p>
  <strong>File URL:</strong>
  <%= @upload.datafile.url %>
</p>

<p>
  <strong>File Path:</strong>
  <%= @upload.datafile.current_path %>
</p>

<p>
  <strong>File Identifier:</strong>
  <%= @upload.datafile.identifier %>
</p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>

app/views/layouts/blimp/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blimp</title>
  <%= stylesheet_link_tag    "blimp/application", media: "all" %>
  <%= javascript_include_tag "blimp/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>